apiVersion: v1
kind: Service
metadata:
  name: zesty-service
spec:
  type: NodePort
  selector:
    app: zesty
  ports:
    - port: 3000       # Kubernetes service port
      targetPort: 3000 # Container port
      nodePort: 30080  # Minikube external access port
